sudo: required
services:
  - docker

before_install:
  - docker build -t arduinohack/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arduinohack/react-test npm test -- --coverage

after_success:
  - docker build -t arduinohack/multi-client ./client
  - docker build -t arduinohack/multi-nginx ./nginx
  - docker build -t arduinohack/multi-server ./server
  - docker build -t arduinohack/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push arduinohack/multi-client
  - docker push arduinohack/multi-nginx
  - docker push arduinohack/multi-server
  - docker push arduinohack/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-918174866571
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

